const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
const readStorage = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch (error) { localStorage.removeItem(key); return fallback; } };
const nativeFetch = window.fetch.bind(window);
let activeDownloadButton;
const showDownloadProgress = detail => { if (activeDownloadButton && activeDownloadButton.textContent !== 'Analyzed') activeDownloadButton.textContent = detail; const status = document.querySelector('#steam-gc-status'); if (status) status.textContent = detail; };
window.fetch = async (...args) => { const requestUrl = String(args[0] instanceof Request ? args[0].url : args[0]); if (!activeDownloadButton && requestUrl.includes('/api/steam/gc/download')) activeDownloadButton = document.activeElement?.closest('.replay-download,[data-gc-index]'); const response = await nativeFetch(...args); if (!requestUrl.includes('/api/steam/gc/download') || requestUrl.includes('/status') || response.status !== 202) return response; const started = await response.json(); if (!started.job) return new Response(JSON.stringify({error: started.error || 'Could not start replay download.'}), {status: 500, headers: {'Content-Type': 'application/json'}}); while (true) { await new Promise(resolve => setTimeout(resolve, 700)); const progress = await nativeFetch('/api/steam/gc/download/status?job=' + encodeURIComponent(started.job)); const job = await progress.json(); showDownloadProgress(job.detail || 'Processing replay locally…'); if (job.state === 'complete') { activeDownloadButton = null; return new Response(JSON.stringify({ok: true, result: job.result}), {status: 200, headers: {'Content-Type': 'application/json'}}); } if (job.state === 'failed' || !progress.ok) { activeDownloadButton = null; return new Response(JSON.stringify({error: job.detail || 'Replay download failed.'}), {status: 400, headers: {'Content-Type': 'application/json'}}); } } };
let matches = readStorage('freetify-matches', []);
let analyses = readStorage('freetify-analyses', []);
if (!analyses.length && matches.length && !matches.some(match => match[1] === 'Parsed demo' || match[1] === 'Steam demo')) matches = [];
const analysisKey = result => String(result?.match_id || result?.demo_hash || result?.stored_file || result?.file || '');
const analysisDate = result => { const date = Date.parse(result?.saved_at || ''); return Number.isFinite(date) ? date : 0; };
const displayDate = result => analysisDate(result) ? new Date(analysisDate(result)).toLocaleDateString() : 'Saved locally';
function normalizeMatchLibrary() { const seen = new Set(), oldMatchIndexes = new Set(); analyses = analyses.filter(result => { const key = analysisKey(result); if (!key || seen.has(key)) return false; seen.add(key); if (Number.isInteger(result.matchIndex)) oldMatchIndexes.add(result.matchIndex); return true; }).sort((a, b) => analysisDate(b) - analysisDate(a)); const analysisKeys = new Set(analyses.map(analysisKey)); const pending = matches.filter((match, index) => !oldMatchIndexes.has(index) && (!match[7] || !analysisKeys.has(String(match[7])))); const analyzed = analyses.map(result => { const player = (result.players || []).find(candidate => candidate.player === result.primary_player) || [...(result.players || [])].sort((a, b) => b.kills - a.kills)[0] || {}; return [result.header?.map_name || result.header?.map || 'Unknown', 'Steam demo', result.match_result || 'ANALYZED', `${result.round_wins || 0} : ${result.round_losses || 0}`, `${player.match_rating ?? player.kd ?? '—'}`, `${player.kills || 0} / ${player.deaths || 0}`, displayDate(result), analysisKey(result), analysisDate(result)]; }); matches = [...analyzed, ...pending].sort((a, b) => Number(b[8] || Date.parse(b[6]) || 0) - Number(a[8] || Date.parse(a[6]) || 0)); analyses.forEach(result => { result.matchIndex = matches.findIndex(match => String(match[7]) === analysisKey(result)); }); }
const row = (m, index) => { const replay = /^https?:\/\/replay[0-9]+\.valve\.net\/730\/.*\.dem\.bz2$/i.test(String(m[0] || '')); const map = replay ? 'Valve matchmaking' : m[0]; return `<div class="match-row match-link" data-match-index="${index}" data-match-key="${escapeHtml(m[7] || '')}" tabindex="0"><span class="map-name">${escapeHtml(map)} <small class="map-mode">${escapeHtml(m[1])}</small></span><span class="result ${m[2] === 'WIN' ? 'win' : m[2] === 'LOSS' ? 'loss' : ''}">${escapeHtml(m[2])} &nbsp; <em>${escapeHtml(m[3])}</em></span><span class="rating">${replay ? `<button class="button secondary replay-download" data-replay-index="${index}">Download &amp; analyze</button>` : escapeHtml(m[4])}</span><span class="kd">${escapeHtml(m[5])}</span><span class="date">${escapeHtml(m[6])}</span><span class="row-arrow">›</span></div>`; };
function renderDashboardStats() { if (!analyses.length) return; const players = analyses.flatMap(item => Array.isArray(item.players) ? [item.players.find(player => player.player === item.primary_player) || item.players[0]].filter(Boolean) : []); const kills = players.reduce((sum, player) => sum + (player.kills || 0), 0); const deaths = players.reduce((sum, player) => sum + (player.deaths || 0), 0); const wins = analyses.reduce((sum, item) => sum + (item.round_wins || 0), 0), losses = analyses.reduce((sum, item) => sum + (item.round_losses || 0), 0); const scored = players.filter(player => player.impact); const impact = scored.reduce((sum, player) => sum + player.impact, 0) / Math.max(scored.length, 1); document.querySelector('#stat-rating').textContent = scored.length ? impact.toFixed(2) : '—'; document.querySelector('#stat-rating-trend').innerHTML = scored.length ? 'Freetify impact <span>your parsed demo events</span>' : 'No impact score <span>raw demo data loaded</span>'; document.querySelector('#stat-winrate').innerHTML = wins + losses ? `${(wins / (wins + losses) * 100).toFixed(1)}<span class="unit">%</span>` : '—<span class="unit">%</span>'; document.querySelector('#stat-winrate-trend').innerHTML = wins + losses ? `${wins} W / ${losses} L <span>parsed round results</span>` : 'No round results <span>in this demo set</span>'; document.querySelector('#stat-kd').textContent = (kills / Math.max(deaths, 1)).toFixed(2); document.querySelector('#stat-kd-trend').innerHTML = `${kills} K / ${deaths} D <span>your parsed events</span>`; }
document.querySelector('#stat-rating').parentElement.querySelector('.stat-label').firstChild.textContent = 'Impact Score ';
function renderMatches() { normalizeMatchLibrary(); try { localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); } catch (_) {} const empty = '<div class="empty-state"><strong>No analyzed demos yet</strong><p class="muted">Choose a demo folder or connect Steam, then scan to build your match history.</p></div>'; document.querySelector('#recent-matches').innerHTML = matches.length ? matches.slice(0, 4).map((m, i) => row(m, i)).join('') : empty; document.querySelector('#all-matches').innerHTML = matches.length ? matches.map((m, i) => row(m, i)).join('') : empty; document.querySelector('.count').textContent = matches.length; renderDashboardStats(); }
renderMatches();
async function restoreLibrary() { if (location.protocol === 'file:') return; try { const response = await fetch('/api/library'); const payload = await response.json(); let restored = 0; [...(payload.results || [])].reverse().forEach(result => { if (!result.stored_file || analyses.some(item => item.stored_file === result.stored_file)) return; const player = (result.players || []).find(candidate => candidate.player === result.primary_player) || [...(result.players || [])].sort((a, b) => b.kills - a.kills)[0]; if (!player) return; analyses = analyses.map(item => ({...item, matchIndex: item.matchIndex + 1})); matches.unshift([result.header?.map_name || result.header?.map || 'Unknown', 'Steam demo', result.match_result || 'ANALYZED', `${result.round_wins || 0} : ${result.round_losses || 0}`, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Saved locally']); analyses.unshift({...result, matchIndex: 0}); restored += 1; }); if (restored) { localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches(); } } catch (_) {} }
async function migrateLegacyLibrary() { if (location.protocol === 'file:' || !analyses.length) return; const legacy = analyses.filter(result => !result.summary_only); if (!legacy.length) return; try { const response = await fetch('/api/library/import', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({results: legacy})}); if (response.ok) localStorage.removeItem('freetify-analyses'); } catch (_) {} }
migrateLegacyLibrary().finally(restoreLibrary);
window.addEventListener('pagehide', () => localStorage.removeItem('freetify-analyses'));
function renderPerformanceChart() { const stats = document.querySelector('.stat-grid'); if (!stats) return; let card = document.querySelector('#performance-card'); if (!card) { card = document.createElement('article'); card.id = 'performance-card'; card.className = 'viewer-card'; card.innerHTML = '<div class="section-heading"><h3>Impact trend</h3><span class="viewer-position">local match history</span></div><canvas id="performance-chart" width="900" height="180"></canvas>'; stats.after(card); } const canvas = document.querySelector('#performance-chart'); if (!canvas) return; const values = analyses.slice(0, 12).reverse().map(item => { const player = (item.players || []).find(candidate => candidate.player === item.primary_player) || (item.players || [])[0]; return player?.impact; }).filter(value => Number.isFinite(value)); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); if (!values.length) { ctx.fillStyle = '#aeb5aa'; ctx.font = '14px Manrope, Arial'; ctx.textAlign = 'center'; ctx.fillText('Analyze a demo to build your impact trend', canvas.width / 2, canvas.height / 2); return; } const min = Math.min(...values), max = Math.max(...values), xStep = (canvas.width - 70) / Math.max(values.length - 1, 1); ctx.strokeStyle = '#39412f'; ctx.lineWidth = 1; for (let y = 25; y < canvas.height - 20; y += 35) { ctx.beginPath(); ctx.moveTo(35, y); ctx.lineTo(canvas.width - 25, y); ctx.stroke(); } ctx.strokeStyle = '#a8d95a'; ctx.lineWidth = 3; ctx.beginPath(); values.forEach((value, index) => { const x = 35 + index * xStep, y = canvas.height - 25 - ((value - min) / Math.max(max - min, .01)) * (canvas.height - 55); index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); values.forEach((value, index) => { const x = 35 + index * xStep, y = canvas.height - 25 - ((value - min) / Math.max(max - min, .01)) * (canvas.height - 55); ctx.fillStyle = '#a8d95a'; ctx.beginPath(); ctx.arc(x, y, 5, 0, Math.PI * 2); ctx.fill(); }); }
renderPerformanceChart(); new MutationObserver(renderPerformanceChart).observe(document.querySelector('#recent-matches'), { childList: true });
const views = { dashboard: ['PERSONAL ANALYTICS', 'Overview'], matches: ['MATCH HISTORY', 'Matches'], settings: ['PREFERENCES', 'Settings'], detail: ['MATCH ANALYSIS', 'Match details'] };
function showView(name) { const safe = views[name] ? name : 'dashboard'; document.querySelectorAll('.view').forEach(v => v.classList.remove('active-view')); document.querySelector(`#${safe}-view`).classList.add('active-view'); document.querySelectorAll('.nav-link').forEach(a => a.classList.toggle('active', a.dataset.view === safe)); document.querySelector('#page-kicker').textContent = views[safe][0]; document.querySelector('#page-title').textContent = views[safe][1]; history.replaceState(null, '', `#${safe}`); }
document.querySelectorAll('[data-view]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); showView(a.dataset.view); })); showView(location.hash.slice(1) || 'dashboard');
const steamResult = new URLSearchParams(location.search).get('steam');
document.querySelector('#settings-view').insertAdjacentHTML('afterbegin', '<div class="settings-card steam-card"><div class="setting-title"><div class="setting-symbol">S</div><div><h3>Steam account</h3><p id="steam-status">Connect Steam securely to prepare match-history sync.</p></div><button class="button secondary" id="steam-login">Sign in with Steam</button></div></div>');
document.querySelector('#steam-login').onclick = () => { if (location.protocol === 'file:') { notify('Run the Freetify app to connect Steam'); return; } document.querySelector('#steam-status').textContent = 'Opening Steam sign-in…'; location.href = '/auth/steam'; };
document.querySelector('.steam-card').insertAdjacentHTML('afterend', '<div class="settings-card steam-sync-card"><div class="setting-title"><div class="setting-symbol">↻</div><div><h3>CS2 match sync</h3><p>Paste the Steam API key and two read-only codes from CS2.</p></div></div><div class="sync-fields"><input id="steam-api-key" class="folder-path" type="password" placeholder="Steam Web API key"><input id="steam-auth-code" class="folder-path" type="password" placeholder="Game Authentication Code"><input id="steam-share-code" class="folder-path" type="text" placeholder="Recent CSGO-… match-sharing code"><button class="button primary" id="steam-sync">Sync matches</button></div><small class="saved-note" id="steam-sync-status">Credentials are stored locally in Freetify’s app data.</small></div>');
const oldSyncButton = document.querySelector('#steam-sync'), syncButton = oldSyncButton.cloneNode(true); oldSyncButton.replaceWith(syncButton);
async function pollSteamDownloads(attempts = 12, startingCount = analyses.length) { if (attempts <= 0) { document.querySelector('#steam-sync-status').textContent = 'Finished waiting for Steam downloads. You can scan again later.'; return; } setTimeout(async () => { await scanInstalled(); if (analyses.length > startingCount) document.querySelector('#steam-sync-status').textContent = `${analyses.length} analyzed demo${analyses.length === 1 ? '' : 's'} in your library.`; else pollSteamDownloads(attempts - 1, startingCount); }, 10000); }
syncButton.onclick = async () => { const api_key = document.querySelector('#steam-api-key').value.trim(), auth_code = document.querySelector('#steam-auth-code').value.trim(), share_code = document.querySelector('#steam-share-code').value.trim(); if (!api_key || !auth_code || !share_code) { notify('Enter the Steam API key and both CS2 match-history codes first'); return; } document.querySelector('#steam-sync-status').textContent = 'Finding available matches through Steam…'; try { const saved = await fetch('/api/steam/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_key, auth_code, share_code }) }); if (!saved.ok) throw new Error('Invalid match-history settings'); const response = await fetch('/api/steam/sync'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); showSteamCodes(payload.codes || []); document.querySelector('#steam-sync-status').textContent = `Found ${(payload.codes || []).length} match${(payload.codes || []).length === 1 ? '' : 'es'}. Choose which replay to download.`; } catch (error) { document.querySelector('#steam-sync-status').textContent = error.message || 'Steam sync failed'; } };
function showSteamCodes(codes) { const card = document.querySelector('.steam-sync-card'); let list = document.querySelector('#steam-code-list'); if (!list) { list = document.createElement('div'); list.id = 'steam-code-list'; list.className = 'steam-code-list'; card.append(list); } list.innerHTML = codes.map((code, index) => `<div class="sync-code"><code>${escapeHtml(code)}</code><button class="button secondary" data-share-code="${escapeHtml(code)}">Download${index === 0 ? ' latest' : ''}</button></div>`).join(''); list.querySelectorAll('[data-share-code]').forEach(button => { button.onclick = async () => { button.disabled = true; button.textContent = 'Queued'; try { const response = await fetch('/api/steam/download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ share_code: button.dataset.shareCode }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); document.querySelector('#steam-sync-status').textContent = `Queued ${button.dataset.shareCode}. Freetify is watching for the downloaded demo.`; pollSteamDownloads(); } catch (error) { button.disabled = false; button.textContent = 'Download'; document.querySelector('#steam-sync-status').textContent = error.message || 'Could not queue replay'; } }; }); }
syncButton.onclick = async () => { const api_key = document.querySelector('#steam-api-key').value.trim(), auth_code = document.querySelector('#steam-auth-code').value.trim(), share_code = document.querySelector('#steam-share-code').value.trim(); if (!api_key || !auth_code || !share_code) { notify('Enter the Steam API key and both CS2 match-history codes first'); return; } document.querySelector('#steam-sync-status').textContent = 'Finding available matches through Steam…'; try { const saved = await fetch('/api/steam/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_key, auth_code, share_code }) }); if (!saved.ok) throw new Error('Invalid match-history settings'); const response = await fetch('/api/steam/sync'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); showSteamCodes(payload.codes || []); document.querySelector('#steam-sync-status').textContent = `Found ${(payload.codes || []).length} match${(payload.codes || []).length === 1 ? '' : 'es'}. Choose which replay to download.`; } catch (error) { document.querySelector('#steam-sync-status').textContent = error.message || 'Steam sync failed'; } };
syncButton.onclick = async () => { const api_key = document.querySelector('#steam-api-key').value.trim(), auth_code = document.querySelector('#steam-auth-code').value.trim(), share_code = document.querySelector('#steam-share-code').value.trim(); const status = document.querySelector('#steam-sync-status'); try { if (api_key || auth_code || share_code) { if (!api_key || !auth_code || !share_code) throw new Error('Enter all three Steam sync values, or clear them to use saved credentials'); const saved = await fetch('/api/steam/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_key, auth_code, share_code }) }); const savedPayload = await saved.json(); if (!saved.ok) throw new Error(savedPayload.error || 'Invalid Steam sync settings'); } else { const account = await (await fetch('/api/steam')).json(); if (!account.sync_ready) throw new Error('Enter the Steam API key and both CS2 match-history codes first'); } status.textContent = 'Finding available matches through Steam…'; const response = await fetch('/api/steam/sync'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); showSteamCodes(payload.codes || []); status.textContent = `Found ${(payload.codes || []).length} match${(payload.codes || []).length === 1 ? '' : 'es'}. Choose which replay to download.`; } catch (error) { status.textContent = error.message || 'Steam sync failed'; } };
if (steamResult === 'connected') { showView('settings'); refreshSteamStatus(true); } if (steamResult === 'error') { showView('settings'); refreshSteamStatus(true); if (!document.querySelector('#steam-status').textContent.includes('failed')) document.querySelector('#steam-status').textContent = 'Steam sign-in could not be verified'; }
if (location.protocol !== 'file:') fetch('/api/steam').then(response => response.json()).then(account => { if (account.connected) { document.querySelector('#steam-status').textContent = `Connected · SteamID ${account.steamid}`; document.querySelector('#steam-login').textContent = 'Connected'; } }).catch(() => {});
if (location.protocol !== 'file:') fetch('/api/steam').then(response => response.json()).then(account => { if (account.sync_ready) document.querySelector('#steam-sync-status').textContent = 'Saved Steam sync credentials are ready to use.'; }).catch(() => {});
async function refreshSteamStatus(showErrors = false) { if (location.protocol === 'file:') return; try { const response = await fetch('/api/steam'); const account = await response.json(); if (account.connected) { const status = document.querySelector('#steam-status'); const button = document.querySelector('#steam-login'); if (status) status.textContent = `Connected · SteamID ${account.steamid}`; if (button) button.textContent = 'Connected'; if (showErrors) notify('Steam connected successfully'); return true; } if (showErrors && account.error) document.querySelector('#steam-status').textContent = account.error; } catch (error) { if (showErrors) document.querySelector('#steam-status').textContent = 'Could not check Steam connection'; } return false; }
const steamPoll = setInterval(async () => { if (await refreshSteamStatus()) clearInterval(steamPoll); }, 1500);

// The Game Coordinator route is the preferred Steam sync path. Unlike the
// retired Web API endpoint below it, this is the same CS2 service that owns a
// player's recent-match list. QR approval happens in the official Steam app.
(() => {
  const accountCard = document.querySelector('.steam-card');
  if (!accountCard) return;
  accountCard.insertAdjacentHTML('afterend', '<div class="settings-card steam-gc-card"><div class="setting-title"><div class="setting-symbol">▣</div><div><h3>CS2 match history</h3><p id="steam-gc-status">Connect through the Steam mobile app to load your recent CS2 matches.</p></div><button class="button primary" id="steam-gc-connect">Connect CS2</button></div><div id="steam-gc-qr" style="display:none;margin:18px 0 0 48px"><img alt="Steam sign-in QR code" style="width:220px;height:220px;border-radius:10px;background:#fff;padding:8px"><p class="muted">Scan in the Steam mobile app and approve the sign-in. Freetify never receives your password.</p></div><div class="steam-code-list" id="steam-gc-matches"></div><div id="steam-gc-actions" style="display:none;margin:14px 0 0 48px"><button class="button secondary" id="steam-gc-download-all">Download all available</button><button class="button secondary" id="steam-gc-open-history">Open Steam Match History</button><small class="saved-note" style="display:block;margin-top:9px">Downloads run one at a time so Steam and Freetify stay responsive.</small></div></div>');
  const button = document.querySelector('#steam-gc-connect');
  const status = document.querySelector('#steam-gc-status');
  const qr = document.querySelector('#steam-gc-qr');
  const matchesList = document.querySelector('#steam-gc-matches');
  const actions = document.querySelector('#steam-gc-actions');
  let requesting = false;
  let loadedMatchCount = -1;

  function matchName(match, index, steamid = '') {
    const finalRound = (match.roundstatsall || []).at(-1) || match.roundstats_legacy || {};
    const replayUrl = finalRound.map || match.replay_url || '';
    const map = /^https?:\/\/replay[0-9]+\.valve\.net\/730\/.*\.dem\.bz2$/i.test(replayUrl) ? (match.watchablematchinfo?.game_map || 'Valve matchmaking') : (finalRound.map || match.map || match.map_name || match.watchablematchinfo?.game_map || match.game_map || 'CS2 match');
    const id = match.matchid || match.match_id || match.id || `recent match ${index + 1}`;
    const score = Array.isArray(finalRound.team_scores) && finalRound.team_scores.length >= 2 ? `${finalRound.team_scores[0]} : ${finalRound.team_scores[1]}` : 'Score in Steam';
    const stamp = match.matchtime ? new Date(Number(match.matchtime) * 1000).toLocaleDateString() : 'Recent';
    const duration = Number(finalRound.match_duration || 0);
    const reservation = finalRound.reservation || {};
    let personal = '';
    try { const accountId = Number(BigInt(steamid) & 0xffffffffn), playerIndex = (reservation.account_ids || []).map(Number).indexOf(accountId); if (playerIndex >= 0) personal = `${(finalRound.kills || [])[playerIndex] ?? 0} K / ${(finalRound.deaths || [])[playerIndex] ?? 0} D`; } catch (_) {}
    return {map: String(map), id: String(id), score, stamp, replayUrl: String(replayUrl), duration: duration ? `${Math.round(duration / 60)} min` : '', personal, rounds: finalRound.round || ''};
  }
  function renderGcMatches(items, steamid = '') {
    matchesList.innerHTML = (items || []).map((match, index) => {
      const item = matchName(match, index, steamid);
      const added = matches.some(entry => entry[7] === item.id);
      const action = item.replayUrl ? 'Download & analyze' : (added ? 'Added' : 'Add to Matches');
      return `<div class="sync-code"><span><strong>${escapeHtml(item.map)}</strong><br><code>${escapeHtml([item.score, item.personal, item.rounds ? `${item.rounds} rounds` : '', item.duration, item.stamp].filter(Boolean).join(' · '))}</code></span><button class="button secondary" data-gc-index="${index}" ${!item.replayUrl && added ? 'disabled' : ''}>${action}</button></div>`;
    }).join('');
    matchesList.querySelectorAll('[data-gc-index]').forEach(button => { button.onclick = async () => {
      const index = Number(button.dataset.gcIndex), item = matchName(items[index], index, steamid); activeDownloadButton = button;
      if (item.replayUrl) {
        button.disabled = true; button.textContent = 'Downloading…';
        try {
          const response = await fetch('/api/steam/gc/download', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({replay_url: item.replayUrl, match_id: item.id})});
          const payload = await response.json();
          if (!response.ok) throw new Error(payload.error);
          const result = payload.result, player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0];
          matches = matches.filter(entry => entry[7] !== item.id);
          if (player) {
            analyses = analyses.map(entry => ({...entry, matchIndex: entry.matchIndex + 1}));
            matches.unshift([result.header?.map_name || item.map, 'Steam demo', result.match_result || 'ANALYZED', `${result.round_wins || 0} : ${result.round_losses || 0}`, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now', item.id]);
            analyses.unshift({...result, matchIndex: 0});
          }
          localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50)));
          localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50)));
          renderMatches(); button.textContent = 'Analyzed';
        } catch (error) { button.disabled = false; button.textContent = 'Download & analyze'; status.textContent = error.message || 'Could not download this CS2 replay.'; }
        return;
      }
      const existing = matchesData => matchesData.some(entry => entry[7] === item.id);
      if (!existing(matches)) {
        const entry = [item.map, 'CS2 synced', 'SYNCED', item.score, '—', 'Replay needed', item.stamp];
        entry.push(item.id);
        matches.unshift(entry);
        try { localStorage.setItem('freetify-matches', JSON.stringify(matches)); } catch (_) {}
        if (typeof renderMatches === 'function') renderMatches();
      }
      button.textContent = 'Added'; button.disabled = true;
    }; });
  }
  async function updateGc() {
    try {
      const response = await fetch('/api/steam/gc/status');
      const data = await response.json();
      if (data.detail) status.textContent = data.detail;
      if (data.qr_image) {
        qr.style.display = 'block';
        qr.querySelector('img').src = data.qr_image;
      } else if (data.state === 'ready') qr.style.display = 'none';
      if (data.match_count && data.match_count !== loadedMatchCount) { const results = await (await fetch('/api/steam/gc/results')).json(); if (Array.isArray(results.matches)) { renderGcMatches(results.matches, results.steamid); actions.style.display = 'block'; loadedMatchCount = results.match_count; } }
      if (data.state === 'ready') {
        button.textContent = 'Sync matches';
        button.disabled = false;
        if (!requesting && !data.match_count) {
          requesting = true;
          await fetch('/api/steam/gc/matches');
        }
      } else if (data.state === 'waiting_for_qr' || data.state === 'waiting_for_approval' || data.state === 'connecting' || data.state === 'connecting_gc' || data.state === 'loading_matches') {
        button.textContent = 'Connecting…';
        button.disabled = true;
      } else {
        button.textContent = 'Connect CS2';
        button.disabled = false;
      }
    } catch (_) { status.textContent = 'Could not reach the local Steam bridge.'; }
  }
  button.onclick = async () => {
    if (button.textContent === 'Sync matches') {
      requesting = true;
      loadedMatchCount = -1;
      matchesList.innerHTML = '';
      const response = await fetch('/api/steam/gc/matches');
      const data = await response.json();
      if (!response.ok) status.textContent = data.error || 'Could not request CS2 matches.';
      else status.textContent = data.detail;
    } else {
      button.disabled = true;
      status.textContent = 'Generating a Steam QR code…';
      const response = await fetch('/api/steam/gc/qr', {method: 'POST'});
      const data = await response.json();
      if (!response.ok) { status.textContent = data.error || 'Could not start Steam sign-in.'; button.disabled = false; }
    }
  };
  document.querySelector('#steam-gc-open-history').onclick = async () => {
    const response = await fetch('/api/steam/match-history', {method: 'POST'});
    const data = await response.json();
    if (!response.ok) status.textContent = data.error || 'Could not open Steam Match History.';
  };
  document.querySelector('#steam-gc-download-all').onclick = async event => {
    const downloadAll = event.currentTarget;
    const available = [...matchesList.querySelectorAll('[data-gc-index]')].filter(item => item.textContent.includes('Download'));
    if (!available.length) { status.textContent = 'No downloadable replays are currently available from CS2.'; return; }
    downloadAll.disabled = true;
    for (let index = 0; index < available.length; index += 1) {
      status.textContent = `Downloading replay ${index + 1} of ${available.length}…`;
      await available[index].onclick();
    }
    downloadAll.disabled = false;
    status.textContent = 'Finished downloading all available replays.';
  };
  updateGc();
  setInterval(updateGc, 8000);
})();
const toast = document.querySelector('#toast');
function notify(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); }
const MAP_OVERVIEWS = {de_cache:{x:-2000,y:3250,scale:5.5},de_mirage:{x:-3230,y:1713,scale:5},de_dust2:{x:-2476,y:3239,scale:4.4},de_inferno:{x:-2087,y:3870,scale:4.9},de_nuke:{x:-3453,y:2887,scale:7},de_ancient:{x:-2953,y:2164,scale:5},de_anubis:{x:-2796,y:3328,scale:5.22},de_overpass:{x:-4831,y:1781,scale:5.2},de_vertigo:{x:-3168,y:1762,scale:4},de_train:{x:-2308,y:2078,scale:4.082077}};
let activeViewerAnimation, viewerLoadId = 0;
async function setupViewer(positions, filename = '', mapName = '', rounds = [], deaths = [], roundStarts = [], score = {}) {
  const loadId = ++viewerLoadId;
  const points = (Array.isArray(positions) ? positions : []).filter(p => p && Number.isFinite(Number(p.X)) && Number.isFinite(Number(p.Y)));
  const canvas = document.querySelector('#demo-canvas'); if (!canvas) return; const hero = document.querySelector('.detail-hero'); if (hero && filename) { const openButton = document.createElement('button'); openButton.className = 'button secondary'; openButton.textContent = 'Open full replay in CS2'; openButton.onclick = async () => { try { const response = await fetch('/api/open-demo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ file: filename }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); notify('Opening replay in CS2…'); } catch (error) { notify(error.message || 'Could not open replay in CS2'); } }; hero.append(openButton); }
  if (!points.length) { const ctx = canvas.getContext('2d'); ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#aeb5aa'; ctx.font = '16px Manrope, Arial'; ctx.textAlign = 'center'; ctx.fillText('No player position data was found in this demo', canvas.width / 2, canvas.height / 2); document.querySelector('#viewer-position').textContent = 'No position data'; document.querySelectorAll('#viewer-play, #viewer-back, #viewer-forward').forEach(button => button.disabled = true); return; }
  const framesByTime = new Map(), viewerPosition = document.querySelector('#viewer-position');
  for (let start = 0; start < points.length; start += 5000) { for (const point of points.slice(start, start + 5000)) { const tick = point.tick ?? point.game_time ?? 0, snapshot = framesByTime.get(tick) || []; snapshot.push(point); framesByTime.set(tick, snapshot); } if (viewerPosition) viewerPosition.textContent = `Preparing full replay · ${Math.min(points.length, start + 5000).toLocaleString()} / ${points.length.toLocaleString()} positions`; await new Promise(resolve => requestAnimationFrame(resolve)); if (loadId !== viewerLoadId) return; }
  const frames = [...framesByTime.entries()].sort((a, b) => Number(a[0]) - Number(b[0]));
  const roundEnds = (Array.isArray(rounds) ? rounds : []).map(round => Number(round.tick)).filter(Number.isFinite).sort((a, b) => a - b), deathWindows = new Map();
  for (const death of Array.isArray(deaths) ? deaths : []) { const tick = Number(death.tick), player = death.user_name || death.victim_name || death.player_name, roundEnd = roundEnds.find(end => end >= tick); if (!player || !Number.isFinite(tick) || roundEnd == null) continue; const spawn = points.find(point => point.player_name === player && Number(point.tick) >= roundEnd), spawnX = Number(spawn?.X), spawnY = Number(spawn?.Y); let release = Infinity; if (spawn) { const moved = points.find(point => point.player_name === player && Number(point.tick) > Number(spawn.tick) && Math.hypot(Number(point.X) - spawnX, Number(point.Y) - spawnY) > 24); if (moved) release = Number(moved.tick); } deathWindows.set(player, [...(deathWindows.get(player) || []), [tick, release]]); }
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const point of points) { const x = Number(point.X), y = Number(point.Y); minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y); }
  const normalizedMap = String(mapName).toLowerCase().replace(/^de[-_]?/, '').replace(/[^a-z0-9]/g, ''), key = `de_${normalizedMap}`; const ctx = canvas.getContext('2d'), overview = MAP_OVERVIEWS[key], scrubber = document.querySelector('#viewer-scrubber') || (() => { const input = document.createElement('input'); input.id = 'viewer-scrubber'; input.type = 'range'; input.min = 0; input.setAttribute('aria-label', 'Replay timeline'); input.className = 'viewer-scrubber'; canvas.after(input); return input; })();
  const radar = new Image(); let radarReady = false; if (overview) { radar.onload = () => { radarReady = true; draw(); }; radar.onerror = () => { const status = document.querySelector('#viewer-position'); if (status) status.textContent = 'Radar backdrop unavailable · player positions still loaded'; draw(); }; radar.src = `/assets/maps/${key}.png`; }
  cancelAnimationFrame(activeViewerAnimation); let frame = 0, frameProgress = 0, playing = false, lastAnimationTime = 0, playbackRate = 1;
  scrubber.max = frames.length - 1;
  const pointOnMap = p => overview ? {x:(Number(p.X)-overview.x)/(overview.scale*1024)*canvas.width,y:(overview.y-Number(p.Y))/(overview.scale*1024)*canvas.height} : {x:30+(Number(p.X)-minX)/Math.max(maxX-minX,1)*(canvas.width-60),y:canvas.height-30-(Number(p.Y)-minY)/Math.max(maxY-minY,1)*(canvas.height-60)};
  const firstPlayableFrame = frames.findIndex(frameData => Number(frameData[1]?.[0]?.game_time) >= 15); if (firstPlayableFrame > 0) frame = firstPlayableFrame;
  const interpolatedSnapshot = progress => { const tick = Number(frames[frame]?.[0] || 0), current = frames[frame]?.[1] || [], next = new Map((frames[frame + 1]?.[1] || []).map(point => [point.player_name, point])); return current.filter(point => !(deathWindows.get(point.player_name) || []).some(([from, to]) => tick >= from && tick <= to)).map(point => { const following = next.get(point.player_name); if (!following) return point; return {...point, X: Number(point.X) + (Number(following.X) - Number(point.X)) * progress, Y: Number(point.Y) + (Number(following.Y) - Number(point.Y)) * progress}; }); };
  const draw = (progress = frameProgress) => { const w = canvas.width, h = canvas.height, snapshot = interpolatedSnapshot(progress); ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, w, h); if (radarReady) { ctx.globalAlpha = .92; ctx.drawImage(radar, 0, 0, w, h); ctx.globalAlpha = 1; } else { ctx.strokeStyle = '#39412f'; ctx.lineWidth = 1; for (let x = 40; x < w - 20; x += 52) { ctx.beginPath(); ctx.moveTo(x, 20); ctx.lineTo(x, h - 20); ctx.stroke(); } for (let y = 32; y < h - 20; y += 52) { ctx.beginPath(); ctx.moveTo(20, y); ctx.lineTo(w - 20, y); ctx.stroke(); } } ctx.strokeStyle = '#c8eb61'; ctx.globalAlpha = .5; ctx.strokeRect(1, 1, w - 2, h - 2); ctx.globalAlpha = 1; snapshot.forEach(p => { const {x,y} = pointOnMap(p); if (x < -12 || y < -12 || x > w + 12 || y > h + 12) return; ctx.fillStyle = Number(p.team_num) === 2 ? '#e4b06b' : '#a8d95a'; ctx.beginPath(); ctx.arc(x, y, 6, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#11150e'; ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#f2f4ef'; ctx.font = '11px Manrope, Arial'; ctx.fillText(String(p.player_name || ''), x + 8, y + 3); }); scrubber.value = frame; document.querySelector('#viewer-position').textContent = `${snapshot.length} players · ${frame + 1} / ${frames.length}${radarReady ? ` · ${key.replace('de_', '')}` : ''}`; };
  const stage = document.createElement('div'); stage.className = 'viewer-stage'; canvas.replaceWith(stage); stage.append(canvas); const hud = document.createElement('div'); hud.className = 'pro-hud'; hud.innerHTML = '<table class="pro-hud-table"><thead><tr><th class="pro-team-t">TERRORISTS</th><th class="pro-score"><strong id="hud-score">0 : 0</strong><span id="hud-round-time">ROUND — · —:——</span></th><th class="pro-team-ct">COUNTER-TERRORISTS</th></tr></thead><tbody><tr><td id="hud-t-equipment">—</td><td></td><td id="hud-ct-equipment">—</td></tr></tbody></table>'; stage.before(hud); const overlay = document.createElement('canvas'); overlay.className = 'viewer-overlay'; overlay.width = canvas.width; overlay.height = canvas.height; stage.append(overlay); const overlayCtx = overlay.getContext('2d'); if (!overlayCtx) return;
  const drawOverlay = () => { const tick = Number(frames[frame]?.[0] || 0), current = interpolatedSnapshot(0), next = new Map((frames[frame + 1]?.[1] || []).map(point => [point.player_name, point])); overlayCtx.clearRect(0, 0, overlay.width, overlay.height); overlayCtx.font = '12px DM Mono, monospace'; overlayCtx.fillStyle = '#f2f4ef'; const start = [...(Array.isArray(roundStarts) ? roundStarts : [])].map(round => Number(round.tick)).filter(value => Number.isFinite(value)).sort((a, b) => a - b).filter(value => value <= tick).at(-1); const end = roundEnds.find(value => value > tick); const roundNumber = start == null ? Math.max(1, roundEnds.filter(value => value <= tick).length) : [...(Array.isArray(roundStarts) ? roundStarts : [])].findIndex(round => Number(round.tick) === start) + 1; const seconds = end == null ? 0 : Math.max(0, Math.ceil((end - tick) / 64)); overlayCtx.fillText(`Round ${roundNumber} · ${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`, 16, 24); current.forEach(point => { const {x, y} = pointOnMap(point); if (x < 0 || y < 0 || x > overlay.width || y > overlay.height) return; const yaw = Number(point.yaw), following = next.get(point.player_name), radians = Number.isFinite(yaw) ? -yaw * Math.PI / 180 : following ? Math.atan2(Number(following.Y) - Number(point.Y), Number(following.X) - Number(point.X)) : 0; overlayCtx.strokeStyle = '#ffffff'; overlayCtx.lineWidth = 2; overlayCtx.beginPath(); overlayCtx.moveTo(x, y); overlayCtx.lineTo(x + Math.cos(radians) * 18, y + Math.sin(radians) * 18); overlayCtx.stroke(); const equipment = [point.active_weapon_name, point.armor_value > 0 ? `${point.armor_value} armor` : '', point.helmet ? 'helmet' : '', point.has_defuser ? 'kit' : '', point.has_bomb ? 'bomb' : ''].filter(Boolean).join(' · '); if (equipment) { overlayCtx.font = '9px DM Mono, monospace'; overlayCtx.fillStyle = '#ffffff'; overlayCtx.fillText(equipment, x + 8, y + 15); } }); requestAnimationFrame(drawOverlay); }; requestAnimationFrame(drawOverlay);
  const updateHud = () => { const tick = Number(frames[frame]?.[0] || 0), end = roundEnds.find(value => value > tick), seconds = end == null ? 0 : Math.max(0, Math.ceil((end - tick) / 64)), round = Math.max(1, roundEnds.filter(value => value <= tick).length + 1), current = interpolatedSnapshot(0), equipment = team => current.filter(point => Number(point.team_num) === team).map(point => `${point.player_name}: ${point.active_weapon_name || '—'}`).join('  •  ') || '—'; const scoreEl = document.querySelector('#hud-score'), timeEl = document.querySelector('#hud-round-time'), tEl = document.querySelector('#hud-t-equipment'), ctEl = document.querySelector('#hud-ct-equipment'); if (scoreEl) scoreEl.textContent = `${score.t ?? score.losses ?? 0} : ${score.ct ?? score.wins ?? 0}`; if (timeEl) timeEl.textContent = `ROUND ${round} · ${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; if (tEl) tEl.textContent = equipment(2); if (ctEl) ctEl.textContent = equipment(3); requestAnimationFrame(updateHud); }; requestAnimationFrame(updateHud);
  const step = amount => { frame = Math.max(0, Math.min(frames.length - 1, frame + amount)); frameProgress = 0; draw(); };
  const frameMilliseconds = () => { const current = frames[frame], following = frames[frame + 1]; const gameTime = Number(following?.[1]?.[0]?.game_time) - Number(current?.[1]?.[0]?.game_time); if (Number.isFinite(gameTime) && gameTime > 0) return Math.min(250, Math.max(16, gameTime * 1000)); const ticks = Number(following?.[0]) - Number(current?.[0]); return Math.min(250, Math.max(16, (Number.isFinite(ticks) && ticks > 0 ? ticks / 64 : .0625) * 1000)); };
  const animate = timestamp => { if (!playing) return; if (!lastAnimationTime) lastAnimationTime = timestamp; frameProgress += (timestamp - lastAnimationTime) * playbackRate / frameMilliseconds(); lastAnimationTime = timestamp; while (frameProgress >= 1 && frame < frames.length - 1) { frame += 1; frameProgress -= 1; } if (frame >= frames.length - 1) { frameProgress = 0; playing = false; document.querySelector('#viewer-play').textContent = 'Play'; draw(); return; } draw(); activeViewerAnimation = requestAnimationFrame(animate); };
  scrubber.oninput = () => { frame = Number(scrubber.value); frameProgress = 0; draw(); };
  document.querySelector('#viewer-play').onclick = () => { playing = !playing; document.querySelector('#viewer-play').textContent = playing ? 'Pause' : 'Play'; if (playing) { lastAnimationTime = 0; activeViewerAnimation = requestAnimationFrame(animate); } else cancelAnimationFrame(activeViewerAnimation); };
  const speedControls = document.createElement('div'); speedControls.className = 'viewer-speed-controls'; speedControls.innerHTML = [1, 2, 4, 8].map(rate => `<button class="button secondary${rate === 1 ? ' active' : ''}" data-playback-rate="${rate}">${rate}×</button>`).join(''); document.querySelector('.viewer-controls').after(speedControls); speedControls.querySelectorAll('[data-playback-rate]').forEach(button => { button.onclick = () => { playbackRate = Number(button.dataset.playbackRate); speedControls.querySelectorAll('[data-playback-rate]').forEach(item => item.classList.toggle('active', item === button)); }; });
  document.querySelector('#viewer-back').onclick = () => step(-1); document.querySelector('#viewer-forward').onclick = () => step(1); draw();
}
function setupHistoricalViewer(positions, mapName = '') {
  const canvas = document.querySelector('#demo-canvas');
  if (!canvas) return;
  const points = (Array.isArray(positions) ? positions : []).filter(point => point && Number.isFinite(Number(point.X)) && Number.isFinite(Number(point.Y)));
  const status = document.querySelector('#viewer-position');
  if (!points.length) { status.textContent = 'No position data'; return; }
  const framesByTick = new Map();
  points.forEach(point => { const tick = point.tick ?? point.game_time ?? 0; const frame = framesByTick.get(tick) || []; frame.push(point); framesByTick.set(tick, frame); });
  const frames = [...framesByTick.entries()].sort((a, b) => Number(a[0]) - Number(b[0]));
  const normalized = String(mapName).toLowerCase().replace(/^de[-_]?/, '').replace(/[^a-z0-9]/g, ''), key = `de_${normalized}`, overview = MAP_OVERVIEWS[key], ctx = canvas.getContext('2d');
  const radar = new Image(); let radarReady = false; radar.onload = () => { radarReady = true; draw(); }; radar.src = `/assets/maps/${key}.png`;
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  points.forEach(point => { minX = Math.min(minX, Number(point.X)); maxX = Math.max(maxX, Number(point.X)); minY = Math.min(minY, Number(point.Y)); maxY = Math.max(maxY, Number(point.Y)); });
  const scrubber = document.querySelector('#viewer-scrubber') || (() => { const input = document.createElement('input'); input.id = 'viewer-scrubber'; input.type = 'range'; input.className = 'viewer-scrubber'; input.min = 0; canvas.after(input); return input; })();
  scrubber.max = frames.length - 1; let frame = 0, playing = false, timer;
  const pointOnMap = point => overview ? {x: (Number(point.X) - overview.x) / (overview.scale * 1024) * canvas.width, y: (overview.y - Number(point.Y)) / (overview.scale * 1024) * canvas.height} : {x: 30 + (Number(point.X) - minX) / Math.max(maxX - minX, 1) * (canvas.width - 60), y: canvas.height - 30 - (Number(point.Y) - minY) / Math.max(maxY - minY, 1) * (canvas.height - 60)};
  function draw() { const snapshot = frames[frame]?.[1] || []; ctx.clearRect(0, 0, canvas.width, canvas.height); if (radarReady) ctx.drawImage(radar, 0, 0, canvas.width, canvas.height); else { ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); } snapshot.forEach(point => { const {x, y} = pointOnMap(point); if (x < -12 || y < -12 || x > canvas.width + 12 || y > canvas.height + 12) return; ctx.fillStyle = Number(point.team_num) === 2 ? '#e4b06b' : '#a8d95a'; ctx.beginPath(); ctx.arc(x, y, 6, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#11150e'; ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#f2f4ef'; ctx.font = '11px Manrope, Arial'; ctx.fillText(String(point.player_name || ''), x + 8, y + 3); }); scrubber.value = frame; status.textContent = `${snapshot.length} players · ${frame + 1} / ${frames.length}`; }
  const step = amount => { frame = Math.max(0, Math.min(frames.length - 1, frame + amount)); draw(); };
  document.querySelector('#viewer-play').onclick = () => { playing = !playing; document.querySelector('#viewer-play').textContent = playing ? 'Pause' : 'Play'; clearInterval(timer); if (playing) timer = setInterval(() => { if (frame >= frames.length - 1) { playing = false; document.querySelector('#viewer-play').textContent = 'Play'; clearInterval(timer); } else step(1); }, 55); };
  document.querySelector('#viewer-back').onclick = () => step(-1); document.querySelector('#viewer-forward').onclick = () => step(1); scrubber.oninput = () => { frame = Number(scrubber.value); draw(); }; draw();
}
function setupReliableViewer(positions, mapName = '', rounds = [], score = {}) {
  const canvas = document.querySelector('#demo-canvas'), status = document.querySelector('#viewer-position');
  if (!canvas || !status) return;
  const points = (Array.isArray(positions) ? positions : []).filter(point => point && Number.isFinite(Number(point.X)) && Number.isFinite(Number(point.Y)));
  if (!points.length) { status.textContent = 'No player position data'; return; }
  const framesByTick = new Map();
  points.forEach(point => { const tick = point.tick ?? point.game_time ?? 0; const frame = framesByTick.get(tick) || []; frame.push(point); framesByTick.set(tick, frame); });
  const frames = [...framesByTick.entries()].sort((a, b) => Number(a[0]) - Number(b[0]));
  const normalized = String(mapName).toLowerCase().replace(/^de[-_]?/, '').replace(/[^a-z0-9]/g, ''), key = `de_${normalized}`, overview = MAP_OVERVIEWS[key];
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  points.forEach(point => { minX = Math.min(minX, Number(point.X)); maxX = Math.max(maxX, Number(point.X)); minY = Math.min(minY, Number(point.Y)); maxY = Math.max(maxY, Number(point.Y)); });
  const stage = document.createElement('div'); stage.className = 'viewer-stage'; canvas.replaceWith(stage);
  const hud = document.createElement('div'); hud.className = 'pro-hud'; hud.innerHTML = '<table class="pro-hud-table"><thead><tr><th class="pro-team-t">TERRORISTS</th><th class="pro-score"><strong id="hud-score">0 : 0</strong><span id="hud-round-time">ROUND —</span></th><th class="pro-team-ct">COUNTER-TERRORISTS</th></tr></thead><tbody><tr><td id="hud-t-equipment">—</td><td></td><td id="hud-ct-equipment">—</td></tr></tbody></table>'; stage.before(hud);
  if (overview) { const map = new Image(); map.className = 'viewer-radar'; map.alt = `${key} radar`; map.src = `/assets/maps/${key}.png`; stage.append(map); }
  stage.append(canvas);
  const scrubber = document.createElement('input'); scrubber.id = 'viewer-scrubber'; scrubber.type = 'range'; scrubber.min = '0'; scrubber.max = String(Math.max(frames.length - 1, 0)); scrubber.className = 'viewer-scrubber'; scrubber.setAttribute('aria-label', 'Replay timeline'); stage.after(scrubber);
  const ctx = canvas.getContext('2d'); let frame = 0, playing = false, timer = null, playbackRate = 1;
  const pointOnMap = point => overview ? {x: (Number(point.X) - overview.x) / (overview.scale * 1024) * canvas.width, y: (overview.y - Number(point.Y)) / (overview.scale * 1024) * canvas.height} : {x: 30 + (Number(point.X) - minX) / Math.max(maxX - minX, 1) * (canvas.width - 60), y: canvas.height - 30 - (Number(point.Y) - minY) / Math.max(maxY - minY, 1) * (canvas.height - 60)};
  const draw = () => { const snapshot = frames[frame]?.[1] || []; ctx.clearRect(0, 0, canvas.width, canvas.height); if (!overview) { ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); } snapshot.forEach(point => { const {x, y} = pointOnMap(point); if (x < -12 || y < -12 || x > canvas.width + 12 || y > canvas.height + 12) return; ctx.fillStyle = Number(point.team_num) === 2 ? '#e4b06b' : '#a8d95a'; ctx.beginPath(); ctx.arc(x, y, 6, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#11150e'; ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#f2f4ef'; ctx.font = '11px Manrope, Arial'; ctx.fillText(String(point.player_name || ''), x + 8, y + 3); }); scrubber.value = String(frame); status.textContent = `${snapshot.length} players · ${frame + 1} / ${frames.length}${overview ? ` · ${key.replace('de_', '')}` : ''}`; };
  const roundEnds = (Array.isArray(rounds) ? rounds : []).map(round => Number(round.tick)).filter(Number.isFinite).sort((a, b) => a - b);
  const updateHud = () => { const tick = Number(frames[frame]?.[0] || 0), round = Math.max(1, roundEnds.filter(end => end <= tick).length + 1), loadout = team => (frames[frame]?.[1] || []).filter(point => Number(point.team_num) === team).map(point => `${point.player_name}: ${point.active_weapon_name || '—'}`).join(' • ') || '—'; document.querySelector('#hud-score').textContent = `${score.t ?? 0} : ${score.ct ?? 0}`; document.querySelector('#hud-round-time').textContent = `ROUND ${round}`; document.querySelector('#hud-t-equipment').textContent = loadout(2); document.querySelector('#hud-ct-equipment').textContent = loadout(3); };
  const step = amount => { frame = Math.max(0, Math.min(frames.length - 1, frame + amount)); draw(); updateHud(); };
  scrubber.oninput = () => { frame = Number(scrubber.value); draw(); updateHud(); };
  document.querySelector('#viewer-back').onclick = () => step(-1);
  document.querySelector('#viewer-forward').onclick = () => step(1);
  const startPlayback = () => { clearInterval(timer); timer = setInterval(() => { if (frame >= frames.length - 1) { playing = false; document.querySelector('#viewer-play').textContent = 'Play'; clearInterval(timer); } else step(1); }, Math.max(8, 55 / playbackRate)); };
  document.querySelector('#viewer-play').onclick = () => { playing = !playing; document.querySelector('#viewer-play').textContent = playing ? 'Pause' : 'Play'; clearInterval(timer); if (playing) startPlayback(); };
  const speeds = document.createElement('div'); speeds.className = 'viewer-speed-controls'; speeds.innerHTML = [1, 2, 4, 8].map(rate => `<button class="button secondary${rate === 1 ? ' active' : ''}" data-playback-rate="${rate}">${rate}×</button>`).join(''); document.querySelector('.viewer-controls').after(speeds); speeds.querySelectorAll('[data-playback-rate]').forEach(button => { button.onclick = () => { playbackRate = Number(button.dataset.playbackRate); speeds.querySelectorAll('[data-playback-rate]').forEach(item => item.classList.toggle('active', item === button)); if (playing) startPlayback(); }; });
  draw(); updateHud();
}
async function detail(index) {
  const match = matches[index]; let analysis = analyses.find(item => item.matchIndex === index);
  const title = match ? `${escapeHtml(match[0])} · ${escapeHtml(match[1])}` : 'Match details';
  if (analysis?.summary_only && analysisKey(analysis)) { document.querySelector('#detail-content').innerHTML = `<div class="settings-card empty-state"><h2>${title}</h2><p class="muted">Loading the full replay and every recorded movement position…</p></div>`; showView('detail'); await new Promise(resolve => requestAnimationFrame(resolve)); try { const response = await fetch('/api/library/report?key=' + encodeURIComponent(analysisKey(analysis))); if (response.ok) { const full = await response.json(); full.matchIndex = index; analyses = analyses.map(item => item === analysis ? full : item); analysis = full; } } catch (_) {} }
  if (!analysis) { document.querySelector('#detail-content').innerHTML = `<div class="settings-card empty-state"><h2>${title}</h2><p class="muted">This match has no stored analysis. Scan a real .dem file to populate its details and event timeline.</p></div>`; showView('detail'); return; }
  const players = [...(Array.isArray(analysis.players) ? analysis.players : [])].sort((a, b) => b.kills - a.kills);
  const events = [...(Array.isArray(analysis.deaths) ? analysis.deaths : [])].sort((a, b) => (a.tick || 0) - (b.tick || 0));
  const positions = Array.isArray(analysis.positions) ? analysis.positions : [];
  const teamByPlayer = new Map(); positions.forEach(point => { if (point.player_name && point.team_num != null) teamByPlayer.set(point.player_name, Number(point.team_num)); });
  const primary = players.find(player => player.player === analysis.primary_player); const primaryTeam = Number(analysis.primary_team ?? primary?.team_num ?? teamByPlayer.get(analysis.primary_player)); const hasTeams = primaryTeam === 2 || primaryTeam === 3;
  const playerTeam = player => Number(player.team_num ?? teamByPlayer.get(player.player));
  const scoreboardRow = player => '<tr class="team-' + (playerTeam(player) === 2 ? 't' : 'ct') + '"><th scope="row">' + escapeHtml(player.player) + '</th><td>' + (player.kills || 0) + '</td><td>' + (player.deaths || 0) + '</td><td>' + (player.kd ?? '—') + '</td><td>' + (player.adr ?? '—') + '</td><td class="impact">' + (player.impact_score ?? '—') + '</td><td>' + (player.headshot_rate ?? 0) + '%</td><td>' + (player.accuracy == null ? '—' : player.accuracy + '%') + '</td><td>' + (player.aim_rating ?? '—') + '</td><td>' + (player.utility_rating ?? '—') + '</td><td>' + (player.utility_damage || 0) + '</td><td>' + (player.flashes || 0) + '</td></tr>';
  const teamRows = (roster, label, team) => roster.length ? '<tr class="team-divider team-' + (team === 2 ? 't' : 'ct') + '"><td colspan="12"><strong>' + label + '</strong><span>' + (team === 2 ? 'Terrorists' : 'Counter-Terrorists') + '</span></td></tr>' + roster.map(scoreboardRow).join('') : '';
  const friendly = hasTeams ? players.filter(player => playerTeam(player) === primaryTeam) : players; const opponents = hasTeams ? players.filter(player => playerTeam(player) !== primaryTeam) : [];
  const scoreboardRows = hasTeams ? teamRows(friendly, 'Your team', primaryTeam) + teamRows(opponents, 'Opponents', primaryTeam === 2 ? 3 : 2) : players.map(scoreboardRow).join('');
  document.querySelector('#detail-content').innerHTML = `<div class="detail-hero"><div><div class="eyebrow">${escapeHtml(analysis.file)}</div><h2>${title}</h2><p class="muted">Parsed locally · ${analysis.rounds?.length || 0} round events · ${events.length} kill events</p></div><button class="button secondary" data-view="matches">← Back to matches</button></div><div class="viewer-card"><div class="section-heading"><h3>Replay viewer · full-path movement samples</h3><span class="viewer-position" id="viewer-position">No position data</span></div><canvas id="demo-canvas" width="900" height="600"></canvas><div class="viewer-controls"><button class="button secondary" id="viewer-back">‹</button><button class="button primary" id="viewer-play">Play</button><button class="button secondary" id="viewer-forward">›</button></div></div><div class="detail-grid"><article class="stat-card"><div class="stat-label">Players</div><div class="stat-value">${players.length}</div></article><article class="stat-card"><div class="stat-label">Rounds</div><div class="stat-value">${analysis.rounds?.length || 0}</div></article><article class="stat-card"><div class="stat-label">Kills logged</div><div class="stat-value">${events.length}</div></article></div><div class="detail-columns scoreboard-columns"><div><div class="section-heading"><h3>Player scoreboard</h3></div><div class="table-card scoreboard-wrap"><table class="scoreboard"><thead><tr><th>Player</th><th>K</th><th>D</th><th>K/D</th><th>ADR</th><th>Impact</th><th>HS%</th><th>Accuracy</th><th>Aim</th><th>Utility</th><th>Util dmg</th><th>Flashes</th></tr></thead><tbody>${players.map(p => `<tr><th scope="row">${escapeHtml(p.player)}</th><td>${p.kills || 0}</td><td>${p.deaths || 0}</td><td>${p.kd ?? '—'}</td><td>${p.adr ?? '—'}</td><td class="impact">${p.impact_score ?? '—'}</td><td>${p.headshot_rate ?? 0}%</td><td>${p.accuracy == null ? '—' : `${p.accuracy}%`}</td><td>${p.aim_rating ?? '—'}</td><td>${p.utility_rating ?? '—'}</td><td>${p.utility_damage || 0}</td><td>${p.flashes || 0}</td></tr>`).join('') || '<tr><td colspan="12" class="muted detail-empty">No player events were found.</td></tr>'}</tbody></table></div></div></div>`;
  const viewerCanvas = document.querySelector('#demo-canvas'); viewerCanvas.width = 900; viewerCanvas.height = 900;
  document.querySelector('.scoreboard tbody').innerHTML = scoreboardRows || '<tr><td colspan="12" class="muted detail-empty">No player events were found.</td></tr>';
  showView('detail');
  try { setupReliableViewer(positions, analysis.header?.map_name || analysis.header?.map || match?.[0] || '', analysis.rounds, {t: analysis.primary_team === 2 ? analysis.round_wins : analysis.round_losses, ct: analysis.primary_team === 3 ? analysis.round_wins : analysis.round_losses}); } catch (error) { console.error('Could not initialize replay viewer', error); notify('Match opened, but its replay viewer could not be loaded.'); }
  document.querySelectorAll('#detail-content [data-view]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); showView(a.dataset.view); }));
  const deleteButton = document.createElement('button'); deleteButton.className = 'button secondary danger-button'; deleteButton.textContent = 'Delete match'; deleteButton.onclick = async () => { if (!confirm('Delete this match report and its local demo file? This cannot be undone.')) return; deleteButton.disabled = true; try { const response = await fetch('/api/library/delete', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({key: analysisKey(analysis)})}); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); analyses = analyses.filter(item => item !== analysis); matches = matches.filter(item => String(item[7]) !== analysisKey(analysis)); localStorage.setItem('freetify-matches', JSON.stringify(matches)); localStorage.setItem('freetify-analyses', JSON.stringify(analyses)); renderMatches(); showView('matches'); notify('Match deleted from Freetify.'); } catch (error) { deleteButton.disabled = false; notify(error.message || 'Could not delete match.'); } }; document.querySelector('.detail-hero').append(deleteButton);
}
document.addEventListener('click', e => { if (e.target.closest('.replay-download')) return; const target = e.target.closest('.match-link'); if (!target) return; const key = target.dataset.matchKey; const index = key ? matches.findIndex(match => String(match[7] || '') === key) : Number(target.dataset.matchIndex); if (index >= 0) void detail(index); });
document.addEventListener('click', async e => { const button = e.target.closest('.replay-download'); if (!button) return; e.preventDefault(); e.stopPropagation(); const index = Number(button.dataset.replayIndex), source = matches[index]; if (!source) return; button.disabled = true; button.textContent = 'Downloading…'; try { const response = await fetch('/api/steam/gc/download', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({replay_url: source[0], match_id: source[7] || ''})}); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); const result = payload.result, player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0]; if (!player) throw new Error('The replay downloaded but did not contain player data.'); matches.splice(index, 1); analyses = analyses.map(entry => ({...entry, matchIndex: entry.matchIndex + 1})); matches.unshift([result.header?.map_name || 'Unknown', 'Steam demo', result.match_result || 'ANALYZED', `${result.round_wins || 0} : ${result.round_losses || 0}`, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now']); analyses.unshift({...result, matchIndex: 0}); localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches(); notify('Replay downloaded and analyzed.'); } catch (error) { button.disabled = false; button.textContent = 'Download & analyze'; notify(error.message || 'Could not download this replay.'); } });
document.addEventListener('keydown', e => { const target = e.target.closest('.match-link'); if (target && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); const key = target.dataset.matchKey; const index = key ? matches.findIndex(match => String(match[7] || '') === key) : Number(target.dataset.matchIndex); if (index >= 0) void detail(index); } });
let selectedFiles = [];
async function scan() { if (!selectedFiles.length) { notify('Choose your demo folder in Settings first'); return; } if (location.protocol === 'file:') { notify('Run the Freetify app for real analysis'); return; } const demos = selectedFiles.filter(file => file.name.toLowerCase().endsWith('.dem')); if (!demos.length) { notify('No .dem files found in that folder'); return; } notify(`Analyzing ${demos.length} demo${demos.length === 1 ? '' : 's'} locally…`); const form = new FormData(); demos.forEach(file => form.append('demos', file, file.name)); try { const response = await fetch('/api/analyze', { method: 'POST', body: form }); const payload = await response.json(); const good = payload.results.filter(result => !result.error); good.forEach(result => { const player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0]; if (!player) return; const header = result.header || {}; const map = header.map_name || header.map || 'Unknown'; const score = `${result.round_wins || 0} : ${result.round_losses || 0}`; const matchIndex = 0; matches.unshift([map, 'Parsed demo', result.match_result || 'ANALYZED', score, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now']); analyses = analyses.map(item => ({ ...item, matchIndex: item.matchIndex + 1 })); analyses.unshift({ ...result, matchIndex }); }); localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches(); notify(`${good.length} demo${good.length === 1 ? '' : 's'} analyzed. ${payload.results.length - good.length ? 'Some files failed.' : ''}`); } catch (error) { notify('Analyzer unavailable — start the Freetify app and try again'); } }
async function scanInstalled() {
  if (selectedFiles.length) return scan();
  if (location.protocol === 'file:') { notify('Run the Freetify app for real analysis'); return; }
  notify('Scanning Steam demo folders locally…');
  try {
    const response = await fetch('/api/scan'); const payload = await response.json(); const good = payload.results.filter(result => !result.error && !analyses.some(item => item.file === result.file));
    good.forEach(result => { const player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0]; if (!player) return; const header = result.header || {}; const map = header.map_name || header.map || 'Unknown'; const score = `${result.round_wins || 0} : ${result.round_losses || 0}`; matches.unshift([map, 'Steam demo', result.match_result || 'ANALYZED', score, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now']); analyses = analyses.map(item => ({ ...item, matchIndex: item.matchIndex + 1 })); analyses.unshift({ ...result, matchIndex: 0 }); });
    localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches();
    const checked = (payload.folders || []).filter(Boolean); notify(good.length ? `${good.length} demo${good.length === 1 ? '' : 's'} analyzed` : checked.length ? `No new demos found. Checked ${checked.length} local folder${checked.length === 1 ? '' : 's'}.` : 'No Steam demo folders were found. Choose a custom folder in Settings.');
  } catch (error) { notify('Could not scan Steam folders — restart Freetify and try again'); }
}
document.querySelector('#scan-button').onclick = scanInstalled; document.querySelector('#matches-scan').onclick = scanInstalled;
if (analyses.length && location.protocol !== 'file:') setTimeout(scanInstalled, 900);
const input = document.querySelector('#folder-input'), path = document.querySelector('#folder-path'); document.querySelector('#choose-folder').onclick = () => input.click(); input.addEventListener('change', () => { selectedFiles = [...input.files]; if (!selectedFiles.length) return; const first = selectedFiles[0]; const parts = first.webkitRelativePath.split('/'); parts.pop(); const chosen = parts.join(' / '); path.textContent = chosen || first.name; localStorage.setItem('freetify-folder', chosen); document.querySelector('#saved-note').textContent = `${selectedFiles.filter(file => file.name.toLowerCase().endsWith('.dem')).length} demos ready to analyze`; notify('Folder selected — press Scan for new demos'); });
const stored = localStorage.getItem('freetify-folder'); if (stored) path.textContent = stored;
if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('./sw.js');
