const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
const readStorage = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch (error) { localStorage.removeItem(key); return fallback; } };
let matches = readStorage('freetify-matches', []);
let analyses = readStorage('freetify-analyses', []);
if (!analyses.length && matches.length && !matches.some(match => match[1] === 'Parsed demo' || match[1] === 'Steam demo')) matches = [];
const row = (m, index) => `<div class="match-row match-link" data-match-index="${index}" tabindex="0"><span class="map-name">${escapeHtml(m[0])} <small class="map-mode">${escapeHtml(m[1])}</small></span><span class="result ${m[2] === 'WIN' ? 'win' : m[2] === 'LOSS' ? 'loss' : ''}">${escapeHtml(m[2])} &nbsp; <em>${escapeHtml(m[3])}</em></span><span class="rating">${escapeHtml(m[4])}</span><span class="kd">${escapeHtml(m[5])}</span><span class="date">${escapeHtml(m[6])}</span><span class="row-arrow">›</span></div>`;
function renderDashboardStats() { if (!analyses.length) return; const players = analyses.map(item => item.players.find(player => player.player === item.primary_player) || item.players[0]).filter(Boolean); const kills = players.reduce((sum, player) => sum + (player.kills || 0), 0); const deaths = players.reduce((sum, player) => sum + (player.deaths || 0), 0); const wins = analyses.reduce((sum, item) => sum + (item.round_wins || 0), 0), losses = analyses.reduce((sum, item) => sum + (item.round_losses || 0), 0); const scored = players.filter(player => player.impact); const impact = scored.reduce((sum, player) => sum + player.impact, 0) / Math.max(scored.length, 1); document.querySelector('#stat-rating').textContent = scored.length ? impact.toFixed(2) : '—'; document.querySelector('#stat-rating-trend').innerHTML = scored.length ? 'Freetify impact <span>your parsed demo events</span>' : 'No impact score <span>raw demo data loaded</span>'; document.querySelector('#stat-winrate').innerHTML = wins + losses ? `${(wins / (wins + losses) * 100).toFixed(1)}<span class="unit">%</span>` : '—<span class="unit">%</span>'; document.querySelector('#stat-winrate-trend').innerHTML = wins + losses ? `${wins} W / ${losses} L <span>parsed round results</span>` : 'No round results <span>in this demo set</span>'; document.querySelector('#stat-kd').textContent = (kills / Math.max(deaths, 1)).toFixed(2); document.querySelector('#stat-kd-trend').innerHTML = `${kills} K / ${deaths} D <span>your parsed events</span>`; }
document.querySelector('#stat-rating').parentElement.querySelector('.stat-label').firstChild.textContent = 'Freetify impact ';
function renderMatches() { const empty = '<div class="empty-state"><strong>No analyzed demos yet</strong><p class="muted">Choose a demo folder or connect Steam, then scan to build your match history.</p></div>'; document.querySelector('#recent-matches').innerHTML = matches.length ? matches.slice(0, 4).map((m, i) => row(m, i)).join('') : empty; document.querySelector('#all-matches').innerHTML = matches.length ? matches.map((m, i) => row(m, i)).join('') : empty; document.querySelector('.count').textContent = matches.length; renderDashboardStats(); }
renderMatches();
function renderPerformanceChart() { const stats = document.querySelector('.stat-grid'); if (!stats) return; let card = document.querySelector('#performance-card'); if (!card) { card = document.createElement('article'); card.id = 'performance-card'; card.className = 'viewer-card'; card.innerHTML = '<div class="section-heading"><h3>Impact trend</h3><span class="viewer-position">local match history</span></div><canvas id="performance-chart" width="900" height="180"></canvas>'; stats.after(card); } const canvas = document.querySelector('#performance-chart'); if (!canvas) return; const values = analyses.slice(0, 12).reverse().map(item => { const player = (item.players || []).find(candidate => candidate.player === item.primary_player) || (item.players || [])[0]; return player?.impact; }).filter(value => Number.isFinite(value)); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); if (!values.length) { ctx.fillStyle = '#aeb5aa'; ctx.font = '14px Manrope, Arial'; ctx.textAlign = 'center'; ctx.fillText('Analyze a demo to build your impact trend', canvas.width / 2, canvas.height / 2); return; } const min = Math.min(...values), max = Math.max(...values), xStep = (canvas.width - 70) / Math.max(values.length - 1, 1); ctx.strokeStyle = '#39412f'; ctx.lineWidth = 1; for (let y = 25; y < canvas.height - 20; y += 35) { ctx.beginPath(); ctx.moveTo(35, y); ctx.lineTo(canvas.width - 25, y); ctx.stroke(); } ctx.strokeStyle = '#a8d95a'; ctx.lineWidth = 3; ctx.beginPath(); values.forEach((value, index) => { const x = 35 + index * xStep, y = canvas.height - 25 - ((value - min) / Math.max(max - min, .01)) * (canvas.height - 55); index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); values.forEach((value, index) => { const x = 35 + index * xStep, y = canvas.height - 25 - ((value - min) / Math.max(max - min, .01)) * (canvas.height - 55); ctx.fillStyle = '#a8d95a'; ctx.beginPath(); ctx.arc(x, y, 5, 0, Math.PI * 2); ctx.fill(); }); }
renderPerformanceChart(); new MutationObserver(renderPerformanceChart).observe(document.querySelector('#recent-matches'), { childList: true });
const views = { dashboard: ['PERSONAL ANALYTICS', 'Overview'], matches: ['MATCH HISTORY', 'Matches'], settings: ['PREFERENCES', 'Settings'], detail: ['MATCH ANALYSIS', 'Match details'] };
function showView(name) { const safe = views[name] ? name : 'dashboard'; document.querySelectorAll('.view').forEach(v => v.classList.remove('active-view')); document.querySelector(`#${safe}-view`).classList.add('active-view'); document.querySelectorAll('.nav-link').forEach(a => a.classList.toggle('active', a.dataset.view === safe)); document.querySelector('#page-kicker').textContent = views[safe][0]; document.querySelector('#page-title').textContent = views[safe][1]; history.replaceState(null, '', `#${safe}`); }
document.querySelectorAll('[data-view]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); showView(a.dataset.view); })); showView(location.hash.slice(1) || 'dashboard');
const steamResult = new URLSearchParams(location.search).get('steam');
document.querySelector('#settings-view').insertAdjacentHTML('afterbegin', '<div class="settings-card steam-card"><div class="setting-title"><div class="setting-symbol">S</div><div><h3>Steam account</h3><p id="steam-status">Connect Steam securely to prepare match-history sync.</p></div><button class="button secondary" id="steam-login">Sign in with Steam</button></div></div>');
document.querySelector('#steam-login').onclick = () => { if (location.protocol === 'file:') { notify('Run the Freetify app to connect Steam'); return; } document.querySelector('#steam-status').textContent = 'Opening Steam sign-in…'; location.href = '/auth/steam'; };
document.querySelector('.steam-card').insertAdjacentHTML('afterend', '<div class="settings-card steam-sync-card"><div class="setting-title"><div class="setting-symbol">↻</div><div><h3>CS2 match sync</h3><p>Paste the read-only codes from CS2 to find recent downloadable matches.</p></div></div><div class="sync-fields"><input id="steam-api-key" class="folder-path" type="password" placeholder="Steam Web API key"><input id="steam-auth-code" class="folder-path" type="password" placeholder="Game Authentication Code"><input id="steam-share-code" class="folder-path" type="text" placeholder="Recent CSGO-… match-sharing code"><button class="button primary" id="steam-sync">Sync matches</button></div><small class="saved-note" id="steam-sync-status">Codes stay in memory and are never saved to disk.</small></div>');
const oldSyncButton = document.querySelector('#steam-sync'), syncButton = oldSyncButton.cloneNode(true); oldSyncButton.replaceWith(syncButton);
async function pollSteamDownloads(attempts = 12, startingCount = analyses.length) { if (attempts <= 0) { document.querySelector('#steam-sync-status').textContent = 'Finished waiting for Steam downloads. You can scan again later.'; return; } setTimeout(async () => { await scanInstalled(); if (analyses.length > startingCount) document.querySelector('#steam-sync-status').textContent = `${analyses.length} analyzed demo${analyses.length === 1 ? '' : 's'} in your library.`; else pollSteamDownloads(attempts - 1, startingCount); }, 10000); }
syncButton.onclick = async () => { const api_key = document.querySelector('#steam-api-key').value.trim(), auth_code = document.querySelector('#steam-auth-code').value.trim(), share_code = document.querySelector('#steam-share-code').value.trim(); if (!api_key || !auth_code || !share_code) { notify('Enter the Steam API key and both match-history codes first'); return; } document.querySelector('#steam-sync-status').textContent = 'Syncing recent matches through Steam…'; try { const saved = await fetch('/api/steam/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_key, auth_code, share_code }) }); if (!saved.ok) throw new Error('Invalid Steam sync settings'); const response = await fetch('/api/steam/sync'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); document.querySelector('#steam-sync-status').textContent = `Steam queued ${payload.launched || 0} replay${payload.launched === 1 ? '' : 's'}. Freetify is watching for them.`; pollSteamDownloads(); } catch (error) { document.querySelector('#steam-sync-status').textContent = error.message || 'Steam sync failed'; } };
function showSteamCodes(codes) { const card = document.querySelector('.steam-sync-card'); let list = document.querySelector('#steam-code-list'); if (!list) { list = document.createElement('div'); list.id = 'steam-code-list'; list.className = 'steam-code-list'; card.append(list); } list.innerHTML = codes.map((code, index) => `<div class="sync-code"><code>${escapeHtml(code)}</code><button class="button secondary" data-share-code="${escapeHtml(code)}">Download${index === 0 ? ' latest' : ''}</button></div>`).join(''); list.querySelectorAll('[data-share-code]').forEach(button => { button.onclick = async () => { button.disabled = true; button.textContent = 'Queued'; try { const response = await fetch('/api/steam/download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ share_code: button.dataset.shareCode }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); document.querySelector('#steam-sync-status').textContent = `Queued ${button.dataset.shareCode}. Freetify is watching for the downloaded demo.`; pollSteamDownloads(); } catch (error) { button.disabled = false; button.textContent = 'Download'; document.querySelector('#steam-sync-status').textContent = error.message || 'Could not queue replay'; } }; }); }
syncButton.onclick = async () => { const api_key = document.querySelector('#steam-api-key').value.trim(), auth_code = document.querySelector('#steam-auth-code').value.trim(), share_code = document.querySelector('#steam-share-code').value.trim(); if (!api_key || !auth_code || !share_code) { notify('Enter the Steam API key and both match-history codes first'); return; } document.querySelector('#steam-sync-status').textContent = 'Finding available matches through Steam…'; try { const saved = await fetch('/api/steam/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_key, auth_code, share_code }) }); if (!saved.ok) throw new Error('Invalid Steam sync settings'); const response = await fetch('/api/steam/sync'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); showSteamCodes(payload.codes || []); document.querySelector('#steam-sync-status').textContent = `Found ${(payload.codes || []).length} match${(payload.codes || []).length === 1 ? '' : 'es'}. Choose which replay to download.`; } catch (error) { document.querySelector('#steam-sync-status').textContent = error.message || 'Steam sync failed'; } };
if (steamResult === 'connected') { showView('settings'); refreshSteamStatus(true); } if (steamResult === 'error') { showView('settings'); refreshSteamStatus(true); if (!document.querySelector('#steam-status').textContent.includes('failed')) document.querySelector('#steam-status').textContent = 'Steam sign-in could not be verified'; }
if (location.protocol !== 'file:') fetch('/api/steam').then(response => response.json()).then(account => { if (account.connected) { document.querySelector('#steam-status').textContent = `Connected · SteamID ${account.steamid}`; document.querySelector('#steam-login').textContent = 'Connected'; } }).catch(() => {});
async function refreshSteamStatus(showErrors = false) { if (location.protocol === 'file:') return; try { const response = await fetch('/api/steam'); const account = await response.json(); if (account.connected) { const status = document.querySelector('#steam-status'); const button = document.querySelector('#steam-login'); if (status) status.textContent = `Connected · SteamID ${account.steamid}`; if (button) button.textContent = 'Connected'; if (showErrors) notify('Steam connected successfully'); return true; } if (showErrors && account.error) document.querySelector('#steam-status').textContent = account.error; } catch (error) { if (showErrors) document.querySelector('#steam-status').textContent = 'Could not check Steam connection'; } return false; }
const steamPoll = setInterval(async () => { if (await refreshSteamStatus()) clearInterval(steamPoll); }, 1500);
const toast = document.querySelector('#toast');
function notify(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); }
function setupViewer(positions, filename = '') {
  const points = positions.filter(p => Number.isFinite(Number(p.X)) && Number.isFinite(Number(p.Y)));
  const canvas = document.querySelector('#demo-canvas'); if (!canvas) return; const hero = document.querySelector('.detail-hero'); if (hero && filename) { const openButton = document.createElement('button'); openButton.className = 'button secondary'; openButton.textContent = 'Open full replay in CS2'; openButton.onclick = async () => { try { const response = await fetch('/api/open-demo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ file: filename }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); notify('Opening replay in CS2…'); } catch (error) { notify(error.message || 'Could not open replay in CS2'); } }; hero.append(openButton); }
  if (!points.length) { const ctx = canvas.getContext('2d'); ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#aeb5aa'; ctx.font = '16px Manrope, Arial'; ctx.textAlign = 'center'; ctx.fillText('No player position data was found in this demo', canvas.width / 2, canvas.height / 2 - 8); ctx.font = '12px Manrope, Arial'; ctx.fillStyle = '#7e847c'; ctx.fillText('The event timeline below is still available.', canvas.width / 2, canvas.height / 2 + 18); document.querySelector('#viewer-position').textContent = 'Timeline-only'; document.querySelectorAll('#viewer-play, #viewer-back, #viewer-forward').forEach(button => button.disabled = true); return; }
  const ctx = canvas.getContext('2d'), minX = Math.min(...points.map(p => Number(p.X))), maxX = Math.max(...points.map(p => Number(p.X))), minY = Math.min(...points.map(p => Number(p.Y))), maxY = Math.max(...points.map(p => Number(p.Y))), scrubber = document.querySelector('#viewer-scrubber') || (() => { const input = document.createElement('input'); input.id = 'viewer-scrubber'; input.type = 'range'; input.min = 0; input.setAttribute('aria-label', 'Replay timeline'); input.className = 'viewer-scrubber'; input.style.width = '100%'; input.style.marginTop = '14px'; canvas.after(input); return input; })();
  let frame = 0, playing = false, timer;
  scrubber.max = points.length - 1;
  const draw = () => { const w = canvas.width, h = canvas.height; ctx.fillStyle = '#20231f'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = '#39412f'; ctx.lineWidth = 1; for (let x = 40; x < w - 20; x += 52) { ctx.beginPath(); ctx.moveTo(x, 20); ctx.lineTo(x, h - 20); ctx.stroke(); } for (let y = 32; y < h - 20; y += 52) { ctx.beginPath(); ctx.moveTo(20, y); ctx.lineTo(w - 20, y); ctx.stroke(); } ctx.strokeStyle = '#69755a'; ctx.lineWidth = 2; ctx.strokeRect(22, 22, w - 44, h - 44); const visible = points.slice(0, frame + 1); visible.forEach((p, i) => { const x = 30 + (Number(p.X) - minX) / Math.max(maxX - minX, 1) * (w - 60), y = h - 30 - (Number(p.Y) - minY) / Math.max(maxY - minY, 1) * (h - 60); ctx.fillStyle = Number(p.team_num) === 2 ? '#e4b06b' : '#a8d95a'; ctx.globalAlpha = i === frame ? 1 : .2; ctx.beginPath(); ctx.arc(x, y, i === frame ? 7 : 3, 0, Math.PI * 2); ctx.fill(); }); ctx.globalAlpha = 1; scrubber.value = frame; document.querySelector('#viewer-position').textContent = `${frame + 1} / ${points.length}`; };
  const step = amount => { frame = Math.max(0, Math.min(points.length - 1, frame + amount)); draw(); };
  scrubber.oninput = () => { frame = Number(scrubber.value); draw(); };
  document.querySelector('#viewer-play').onclick = () => { playing = !playing; document.querySelector('#viewer-play').textContent = playing ? 'Pause' : 'Play'; if (playing) { timer = setInterval(() => { if (frame >= points.length - 1) { playing = false; clearInterval(timer); document.querySelector('#viewer-play').textContent = 'Play'; } else step(1); }, 180); } else clearInterval(timer); };
  document.querySelector('#viewer-back').onclick = () => step(-1); document.querySelector('#viewer-forward').onclick = () => step(1); draw();
}
function detail(index) {
  const match = matches[index], analysis = analyses.find(item => item.matchIndex === index);
  const title = match ? `${escapeHtml(match[0])} · ${escapeHtml(match[1])}` : 'Match details';
  if (!analysis) { document.querySelector('#detail-content').innerHTML = `<div class="settings-card empty-state"><h2>${title}</h2><p class="muted">This match has no stored analysis. Scan a real .dem file to populate its details and event timeline.</p></div>`; showView('detail'); return; }
  const players = [...(analysis.players || [])].sort((a, b) => b.kills - a.kills);
  const events = [...(analysis.deaths || [])].sort((a, b) => (a.tick || 0) - (b.tick || 0));
  document.querySelector('#detail-content').innerHTML = `<div class="detail-hero"><div><div class="eyebrow">${escapeHtml(analysis.file)}</div><h2>${title}</h2><p class="muted">Parsed locally · ${analysis.rounds?.length || 0} round events · ${events.length} kill events</p></div><button class="button secondary" data-view="matches">← Back to matches</button></div><div class="viewer-card"><div class="section-heading"><h3>Replay viewer · movement samples</h3><span class="viewer-position" id="viewer-position">No position data</span></div><canvas id="demo-canvas" width="900" height="360"></canvas><div class="viewer-controls"><button class="button secondary" id="viewer-back">‹</button><button class="button primary" id="viewer-play">Play</button><button class="button secondary" id="viewer-forward">›</button></div></div><div class="detail-grid"><article class="stat-card"><div class="stat-label">Players</div><div class="stat-value">${players.length}</div></article><article class="stat-card"><div class="stat-label">Rounds</div><div class="stat-value">${analysis.rounds?.length || 0}</div></article><article class="stat-card"><div class="stat-label">Kills logged</div><div class="stat-value">${events.length}</div></article></div><div class="detail-columns"><div><div class="section-heading"><h3>Player scoreboard</h3></div><div class="table-card player-table">${players.map(p => `<div class="player-row"><strong>${escapeHtml(p.player)}</strong><span>${p.kills} / ${p.deaths}</span><span>K/D ${p.kd}</span><span>${p.headshot_rate}% HS</span><span>${p.damage || 0} dmg</span><span>${p.assists || 0} A</span><span>${p.utility_damage || 0} util</span></div>`).join('') || '<p class="muted detail-empty">No player events were found.</p>'}</div></div><div><div class="section-heading"><h3>Kill timeline</h3></div><div class="timeline">${events.map((e, i) => `<div class="timeline-event"><span class="timeline-dot"></span><span class="timeline-time">#${e.tick ?? i + 1}</span><span><strong>${escapeHtml(e.attacker_name || e.attacker || 'Unknown')}</strong> eliminated <strong>${escapeHtml(e.user_name || e.victim_name || 'Unknown')}</strong><small>${escapeHtml(e.weapon || 'weapon unknown')}${e.headshot ? ' · headshot' : ''}</small></span></div>`).join('') || '<p class="muted detail-empty">No kill events were found.</p>'}</div></div></div>`;
  setupViewer(analysis.positions || [], analysis.stored_file || analysis.file); document.querySelectorAll('#detail-content [data-view]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); showView(a.dataset.view); })); showView('detail');
}
document.addEventListener('click', e => { const target = e.target.closest('.match-link'); if (target) detail(Number(target.dataset.matchIndex)); });
document.addEventListener('keydown', e => { const target = e.target.closest('.match-link'); if (target && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); detail(Number(target.dataset.matchIndex)); } });
let selectedFiles = [];
async function scan() { if (!selectedFiles.length) { notify('Choose your demo folder in Settings first'); return; } if (location.protocol === 'file:') { notify('Run the Freetify app for real analysis'); return; } const demos = selectedFiles.filter(file => file.name.toLowerCase().endsWith('.dem')); if (!demos.length) { notify('No .dem files found in that folder'); return; } notify(`Analyzing ${demos.length} demo${demos.length === 1 ? '' : 's'} locally…`); const form = new FormData(); demos.forEach(file => form.append('demos', file, file.name)); try { const response = await fetch('/api/analyze', { method: 'POST', body: form }); const payload = await response.json(); const good = payload.results.filter(result => !result.error); good.forEach(result => { const player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0]; if (!player) return; const header = result.header || {}; const map = header.map_name || header.map || 'Unknown'; const score = `${result.round_wins || 0} : ${result.round_losses || 0}`; const matchIndex = 0; matches.unshift([map, 'Parsed demo', result.match_result || 'ANALYZED', score, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now']); analyses = analyses.map(item => ({ ...item, matchIndex: item.matchIndex + 1 })); analyses.unshift({ ...result, matchIndex }); }); localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches(); notify(`${good.length} demo${good.length === 1 ? '' : 's'} analyzed. ${payload.results.length - good.length ? 'Some files failed.' : ''}`); } catch (error) { notify('Analyzer unavailable — start the Freetify app and try again'); } }
async function scanInstalled() {
  if (selectedFiles.length) return scan();
  if (location.protocol === 'file:') { notify('Run the Freetify app for real analysis'); return; }
  notify('Scanning Steam demo folders locally…');
  try {
    const response = await fetch('/api/scan'); const payload = await response.json(); const good = payload.results.filter(result => !result.error && !analyses.some(item => item.file === result.file));
    good.forEach(result => { const player = result.players.find(candidate => candidate.player === result.primary_player) || [...result.players].sort((a, b) => b.kills - a.kills)[0]; if (!player) return; const header = result.header || {}; const map = header.map_name || header.map || 'Unknown'; const score = `${result.round_wins || 0} : ${result.round_losses || 0}`; matches.unshift([map, 'Steam demo', result.match_result || 'ANALYZED', score, `${player.kd}`, `${player.kills} / ${player.deaths}`, 'Just now']); analyses = analyses.map(item => ({ ...item, matchIndex: item.matchIndex + 1 })); analyses.unshift({ ...result, matchIndex: 0 }); });
    localStorage.setItem('freetify-matches', JSON.stringify(matches.slice(0, 50))); localStorage.setItem('freetify-analyses', JSON.stringify(analyses.slice(0, 50))); renderMatches();
    const checked = (payload.folders || []).filter(Boolean); notify(good.length ? `${good.length} demo${good.length === 1 ? '' : 's'} analyzed` : checked.length ? `No new demos found. Checked ${checked.length} local folder${checked.length === 1 ? '' : 's'}.` : 'No Steam demo folders were found. Choose a custom folder in Settings.');
  } catch (error) { notify('Could not scan Steam folders — restart Freetify and try again'); }
}
document.querySelector('#scan-button').onclick = scanInstalled; document.querySelector('#matches-scan').onclick = scanInstalled;
if (analyses.length && location.protocol !== 'file:') setTimeout(scanInstalled, 900);
const input = document.querySelector('#folder-input'), path = document.querySelector('#folder-path'); document.querySelector('#choose-folder').onclick = () => input.click(); input.addEventListener('change', () => { selectedFiles = [...input.files]; if (!selectedFiles.length) return; const first = selectedFiles[0]; const parts = first.webkitRelativePath.split('/'); parts.pop(); const chosen = parts.join(' / '); path.textContent = chosen || first.name; localStorage.setItem('freetify-folder', chosen); document.querySelector('#saved-note').textContent = `${selectedFiles.filter(file => file.name.toLowerCase().endsWith('.dem')).length} demos ready to analyze`; notify('Folder selected — press Scan for new demos'); });
const stored = localStorage.getItem('freetify-folder'); if (stored) path.textContent = stored;
if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('./sw.js');
