const matches=[['Mirage','Premier','WIN','13 : 9','1.34','18 / 12','Today'],['Inferno','Premier','WIN','13 : 7','1.21','17 / 11','Yesterday'],['Ancient','Premier','LOSS','8 : 13','0.94','13 / 16','Sep 10'],['Anubis','Competitive','WIN','13 : 10','1.18','21 / 18','Sep 09'],['Nuke','Premier','WIN','13 : 5','1.27','19 / 10','Sep 08'],['Vertigo','Premier','LOSS','11 : 13','1.02','16 / 17','Sep 07'],['Dust II','Competitive','WIN','13 : 6','1.30','20 / 9','Sep 05'],['Mirage','Premier','WIN','13 : 11','1.16','18 / 15','Sep 04']];
const row=m=>`<div class="match-row"><span class="map-name">${m[0]} <small class="map-mode">${m[1]}</small></span><span class="result ${m[2]==='WIN'?'win':'loss'}">${m[2]} &nbsp; <em>${m[3]}</em></span><span class="rating">${m[4]}</span><span class="kd">${m[5]}</span><span class="date">${m[6]}</span><span class="row-arrow">›</span></div>`;
document.querySelector('#recent-matches').innerHTML=matches.slice(0,4).map(row).join('');document.querySelector('#all-matches').innerHTML=matches.map(row).join('');
const views={dashboard:['PERSONAL ANALYTICS','Overview'],matches:['MATCH HISTORY','Matches'],settings:['PREFERENCES','Settings']};
function showView(name){const safe=views[name]?name:'dashboard';document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector(`#${safe}-view`).classList.add('active-view');document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.view===safe));document.querySelector('#page-kicker').textContent=views[safe][0];document.querySelector('#page-title').textContent=views[safe][1];history.replaceState(null,'',`#${safe}`)}
document.querySelectorAll('[data-view]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showView(a.dataset.view)}));showView(location.hash.slice(1)||'dashboard');
const toast=document.querySelector('#toast');let selectedDemoCount=0;function scan(){toast.textContent=selectedDemoCount?`Found ${selectedDemoCount} .dem file${selectedDemoCount===1?'':'s'} in folder`:'Choose your demo folder in Settings first';toast.classList.add('show');setTimeout(()=>{toast.classList.remove('show');toast.textContent='Scanning for demos…'},2500)}document.querySelector('#scan-button').onclick=scan;document.querySelector('#matches-scan').onclick=scan;
const input=document.querySelector('#folder-input'),path=document.querySelector('#folder-path');document.querySelector('#choose-folder').onclick=()=>input.click();input.addEventListener('change',()=>{if(!input.files.length)return;const first=input.files[0];const parts=first.webkitRelativePath.split('/');parts.pop();const chosen=parts.join(' / ');selectedDemoCount=[...input.files].filter(file=>file.name.toLowerCase().endsWith('.dem')).length;path.textContent=chosen||first.name;localStorage.setItem('roundhouse-folder',chosen);document.querySelector('#saved-note').textContent='Folder saved locally';toast.textContent=`Found ${selectedDemoCount} .dem file${selectedDemoCount===1?'':'s'} in folder`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)});const stored=localStorage.getItem('roundhouse-folder');if(stored)path.textContent=stored;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
